name: build-docker-image

on:
  push:
    branches:
    - master

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push current repo code
        id: get-tag
        run: |
          last_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          new_tag=$(echo $last_tag | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
          echo "tag=$new_tag" >> "$GITHUB_OUTPUT"
          git tag $new_tag
          git push origin $new_tag

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.get-tag.outputs.tag }}
